backend:
  name: git-gateway
  branch: main
media_folder: src/assets/uploads
public_folder: /assets/uploads

# Run "npx decap-server" for local backend
local_backend: true
editor:
  preview: false
collections:
  - name: pages
    label: Pages
    files:
      - label: Introduction
        name: introduction
        file: src/collections/pages/introduction.md
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - label: Intro
            name: introSection
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Ground Rules
            name: groundRulesSection
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: How To
            name: howToSection
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Contributors
            name: contributorsSection
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Connect
            name: connectSection
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
      - label: Planning
        name: planning
        file: src/collections/pages/planning.md
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
      - label: Doing
        name: doing
        file: src/collections/pages/doing.md
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
      - label: Reflecting
        name: reflecting
        file: src/collections/pages/reflecting.md
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
  - label: Site Configuration
    name: config
    files:
      - label: Site Configuration
        name: config
        file: src/_data/config.json
        fields:
          - {label: URL, name: url, widget: string}
          - {label: Maximum Posts in RSS Feed, name: maxPostsInFeed, widget: number, min: 1}
  - label: Site Data
    name: data
    files:
      - label: Site Data
        name: site
        file: src/_data/site.json
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Author Name, name: authorName, widget: string}
          - {label: Author Email, name: authorEmail, widget: string}
          - {label: Author Website, name: authorWebsite, widget: string}
